### ISSUE TITLE
header 만들기

### ISSUE THREAD

**Issue by joan-KIM** [joan-KIM/google-meet-clone#1]
- [x] flex 적용하기
- [x] logo image 넣기
- [x] icon, account 사이에 마진
- [x] icon 적용하기
- [x] Meet 글자 꾸미기
- [x] icon 크기 설정 및 정렬

**Comment by ParkEunwoo** [comment]
```html
<link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
```
head태그 안에 추가해주세요

**Comment by joan-KIM** [comment]
- [x] flex 적용하기
- [x] logo image 넣기
- [ ] icon, account 사이에 마진
- [ ] icon 적용하기
- [ ] Meet 글자 꾸미기
- [ ] icon 크기 설정 및 정렬

**Comment by ParkEunwoo** [comment]
```html
<link rel="stylesheet" href="https://egkoppel.github.io/product-sans/google-fonts.css">
```
